# Site Settings
title: MUDASSAR DEVELOPERS
description: "Mudassar Developers Website based on Jekyll"
baseurl: "https://ali1876.github.io/MudassarDev.github.io"
url: ""
tagline: "Mudassar Developers"

#Build Settings
markdown: kramdown
